version: '3.8'
services:
  app:
    build:
      context: .
    command: >
      sh -c "python3 parse.py"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=secretpassword
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local